on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: "!contains(${{ github.event.head_commit.message }}, '#nobuild')"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task build
      - name: Bump version and push tag
        id: BumpVersion
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          INITIAL_VERSION: 1.0.0
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/LxCrypt.exe
            dist/LxCrypt
          tag_name: ${{steps.BumpVersion.outputs.tag}}
          body_path: .github/release_notes.txt
