on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/LxCrypt.exe
            dist/LxCrypt
